flaskr/__init__.py
import os
from flask import Flask, render_template, jsonify

def create_app(test_config=None):
    app = Flask(__name__, instance_relative_config=True)
    app.secret_key = 'dev'
    app.config.from_mapping(
        SECERT_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'flaskr.sqlite')
    )

    if test_config is None:
        app.config.from_pyfile('config.py', silent=True)
    else:
        app.config.from_mapping(test_config)

    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    from . import db
    db.init_app(app)

    return app
    

flaskr/main.py
from flask import jsonify
from flaskr import create_app
from flaskr.utils.error import InvalidAPIUsage
from flaskr.routes import auth, blog

app = create_app()

app.register_blueprint(auth.bp)
app.register_blueprint(blog.bp)
app.add_url_rule('/', endpoint='index')


@app.errorhandler(InvalidAPIUsage)
def invalid_api_usage(e):
    return jsonify(e.to_dict()), e.status_code

@app.errorhandler(404)
def page_not_found(e):
    return jsonify(error=str(e), code = 100), 404

@app.route('/error')
def error():
    raise InvalidAPIUsage('Page not found')


@app.route('/abc')
def abc():
    return 'Hello, World!'

if __name__ == '__main__':
    app.run(port=5002, debug=True)

flaskr/routes/auth.py
import functools
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for,
    current_app
)
from werkzeug.security import check_password_hash, generate_password_hash
from flaskr.db import get_db

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/registry', methods=('GET', 'POST'))
def registry():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None

        if not username:
            error = 'Username is required.'
        if not password:
            error = 'Password is required.'

        if error is None:
            try:
                db.execute(
                    "INSERT INTO user (username, password) VALUES (?, ?)",
                    (username, generate_password_hash(password))
                )
                db.commit()
            except db.IntegrityError:
                error = f"User {username} is already registered."
            else:
                return redirect(url_for('auth.login'))

        flash(error)
    return render_template('auth/registry.html')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None
        user = db.execute(
            'SELECT * FROM user WHERE username = ?',
            (username, )
        ).fetchone()

        if user is None:
            error = 'Incorrent username'
        elif not check_password_hash(user['password'], password):
            error = 'Incorrent password'

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('index'))
        flash(error)
    return render_template('auth/login.html')

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute(
            'SELECT * FROM user WHERE id = ?',
        (user_id,)
        ).fetchone()


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        
        return view(**kwargs)
    return wrapped_view

flaskr/routes/blog.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from werkzeug.exceptions import abort
from flaskr.routes.auth import login_required
from flaskr.db import get_db

bp = Blueprint('blog', __name__)



@bp.route('/')
def index():
    db = get_db()
    posts = db.execute(
        'SELECT p.id, title, body, created, author_id, username'
        ' FROM post p JOIN user u ON p.author_id = u.id'
        ' ORDER BY created DESC'
    ).fetchall()
    return render_template('blog/index.html', posts=posts)

@bp.route('/create', methods=('POST', 'GET'))
def create():
    if request.method == 'POST':
        author_id = g.user['id']
        title = request.form['title']
        body = request.form['body']

        if not author_id:
            return redirect(url_for('auth.login'))

        error = None
        if not title:
            error = 'Title is required.'
        if not body:
            error = 'Body is required.'
        
        if not error:
            db = get_db()
            db.execute(
                'INSERT INTO post (title, body, author_id)'
                ' VALUES(?, ?, ?)',
                (title, body, author_id)
            )
            db.commit()
            return redirect(url_for('blog.index'))
        flash(error)
    return render_template('blog/create.html')

@bp.route('/update/<id>', methods=('GET', 'POST'))
def update(id):
    db = get_db()
    post = db.execute(
            'SELECT * FROM post WHERE id = ?',
            (id,)
        ).fetchone()
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        error = None
        if not post:
            abort(403)
        if not title:
            error = 'Title is required.'
        if not body:
            error = 'Body is required.'
        
        if not error:
            db.execute(
                'UPDATE post SET title = ?, body = ? WHERE id = ?',
                (title, body, id)
            )
            db.commit()
            return redirect(url_for('blog.index'))
        
        flash(error)

    return render_template('blog/update.html', post=post)

flaskr/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} - Flaskr</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <nav>
        <h1>Flaskr</h1>
        <ul>
            {% if g.user %}
            <li><span>{{ g.user['username'] }}</span></li>
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
            {% else %}
            <li><a href="{{ url_for('auth.registry') }}">Registry</a></li>
            <li><a href="{{ url_for('auth.login') }}">Login</a></li>
            {% endif %}
        </ul>
    </nav>

    <section class="content">
        <header>
            {% block header %}{% endblock %}
        </header>
        {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
        {% endfor %}
        {% block content %}{% endblock %}
    </sectin>
</body>
</html>

flaskr/templates/blog/create.html
{% extends 'base.html' %}

{% block header %}
    {% block title %} Blog-create {% endblock %}
{% endblock %}

{% block content %}


<form method="post">
    <label for="title" name="title">Title</label>
    <input type="text" name="title" >
    <label for="body" name="'body">Body</label>
    <textarea name="body" cols="30" rows="10"></textarea>
    <input type="submit">
</form>

{% endblock %}

flaskr/templates/blog/index.html
{% extends 'base.html' %} {% block header %}
<h1>{% block title %} Posts{% endblock %}</h1>
{% if g.user %}
<a href="{{url_for('blog.create')}}">New</a>
{% endif %} {% endblock %} {% block content %} {% for post in posts %}
<article class="post">
  <header>
    <div>
      <h1>{{post['title']}}</h1>
      <div class="about">
        by {{post['username']}} on{{post['created'].strftime('%Y-%m-%d')}}
      </div>
      {% if g.user['id'] == post['author_id'] %}
      <a href="{{url_for('blog.update', id=post['id'])}}" class="action"
        >Edit</a
      >
      {% endif %}
    </div>
  </header>
  <p class="body">{{post['body']}}</p>
</article>
{% if not loop.last %}
<hr />
{% endif %} {% endfor %} {% endblock %}

flaskr/templates/blog/update.html
{% extends 'base.html' %} {% block header %}

<h1>{% block title %} Update Blog {% endblock %}</h1>

{% endblock %} {% block content %}

<form method="post">
  <label for="title" name="title">Title</label>
  <input type="text" name="title" value="{{post['title']}}" />
  <label for="body" name="'body">Body</label>
  <textarea name="body" cols="30" rows="10">{{post['body']}}</textarea>
  <input type="submit" />
</form>

{% endblock %}

flaskr/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    I am "{{ g.user['username'] }}"
  </body>
</html>

flaskr/templates/page_not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    404 Not Found
</body>
</html>